clean: remove large sqlite profiling artifacts before push

diff --git a/aspp_26_cw2_mem50/jobs/run-cw2-profile-nsys-a100.yml b/aspp_26_cw2_mem50/jobs/run-cw2-profile-nsys-a100.yml
--- a/aspp_26_cw2_mem50/jobs/run-cw2-profile-nsys-a100.yml
+++ b/aspp_26_cw2_mem50/jobs/run-cw2-profile-nsys-a100.yml
@@ -1,9 +1,9 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  generateName: awave-cw2-ncu-a100-
+  generateName: awave-cw2-nsys-a100-
   labels:
-    kueue.x-k8s.io/max-exec-time-seconds: "300"
+    kueue.x-k8s.io/max-exec-time-seconds: "600"
     kueue.x-k8s.io/queue-name: eidf018ns-profiling-queue
 spec:
   completions: 1
@@ -11,9 +11,9 @@ spec:
   ttlSecondsAfterFinished: 1800
   template:
     metadata:
-      name: awave-cw2-ncu-a100
+      name: awave-cw2-nsys-a100
     spec:
-      activeDeadlineSeconds: 300
+      activeDeadlineSeconds: 600
       containers:
       - name: run
         image: $container
@@ -32,13 +32,13 @@ spec:
               cmake -S src -B build-cuda -DAWAVE_MODE=CUDA -DCMAKE_BUILD_TYPE=Release;
               cmake --build build-cuda -j;
             fi;
-            if ! command -v ncu >/dev/null 2>&1; then
-              echo "ncu not found in container PATH";
+            if ! command -v nsys >/dev/null 2>&1; then
+              echo "nsys not found in container PATH";
               exit 127;
             fi;
-            mkdir -p /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/ncu;
-            ncu --set default --target-processes all --force-overwrite true --export /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/ncu/cw2_ncu_a100_np1 build-cuda/awave -skip_cpu 1 -mpi 1,1,1 -shape 256,256,256 -nsteps 16 -out_period 8 -io 0 -json /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/ncu/cw2_ncu_a100_np1.json /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/ncu/cw2_ncu_a100_np1;
-            ls -lh /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/ncu;
+            mkdir -p /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/nsys;
+            nsys profile -f true --trace=cuda,nvtx,mpi --sample=none -o /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/nsys/cw2_nsys_a100_np1 mpirun -np 1 build-cuda/awave -skip_cpu 1 -mpi 1,1,1 -shape 512,512,256 -nsteps 12 -out_period 6 -io 0 -json /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/nsys/cw2_nsys_a100_np1.json /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/nsys/cw2_nsys_a100_np1;
+            ls -lh /home/eidf018/eidf018/shared/s2792840-epcc-pvc/ASPP_CW2/aspp_26_cw2/logs/profiles/nsys;
         resources:
           requests:
             cpu: 4
